### ISSUE TITLE
completionHandler not called when Offline

### ISSUE THREAD

**Issue by winkelsdorf** [JanGorman/MapleBacon#20]
I'd been thinking about the use case where a User is temporarily offline (detected via Reachability) and how to re-try downloading after Reachability changed back to online.

Easiest way would probably be to set a Bool inside the completion handler upon successful download, while trying to download when Reachability turned online and Bool is false.

I tried to implement a completion handler, in order to check if an Image has been downloaded.

``` swift
        if let imageURL = NSURL(string: "https://abc.xyz/img/g-icon.jpg"), placeholder = UIImage(named: "Dummy") {
            imageView.setImageWithURL(imageURL, placeholder:placeholder, completion: { imageInstance, error in
                if let error = error as NSError? {
                    NSLog(error.description)
                }
            })
```

The completion handler is never triggered when offline.

For my tests I adjusted the SessionConfiguration in ImageDownloadOperation.swift

``` swift
        let sessionConfiguration = NSURLSessionConfiguration.defaultSessionConfiguration()
        sessionConfiguration.timeoutIntervalForRequest = 5.0
        sessionConfiguration.timeoutIntervalForResource = 5.0
```

Line 97 of ImageDownloadOperation.swift is reached in debugger

``` swift
    public func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?) {
        if let error = error {
            completionHandler?(nil, error) // reached
            finished = true
        }
    }
```

which in turn calls downloadHandlerWithStorage in ImageManager.swift.

See Debugger:

<img width="1136" alt="screenshot 2015-09-05 13 29 05" src="https://cloud.githubusercontent.com/assets/1413291/9699035/364fb35a-53d2-11e5-9047-c5c5df04bf7d.png">

Furthermore completion handler in downloadOperationWithURL in ImageViewExtension.swift is never called with that error, but the method is reached.

``` swift
    private func downloadOperationWithURL(url: NSURL, placeholder: UIImage? = nil, crossFadePlaceholder crossFade: Bool = true,
            cacheScaled: Bool = false, completion: ImageDownloaderCompletion? = nil) -> ImageDownloadOperation? {
            return ImageManager.sharedManager.downloadImageAtURL(url, cacheScaled: cacheScaled, imageView: self) {
            [weak self] imageInstance, error in
            dispatch_async(dispatch_get_main_queue()) {
                if let image = imageInstance?.image {
                    if let _ = placeholder where crossFade {
                        self?.layer.addAnimation(CATransition(), forKey: nil)
                    }
                    self?.image = image
                }
                completion?(imageInstance, error)
            }
        }
    }
```

**Comment by LappleApple** [comment]
@JanGorman Hi, did you end up getting back to @winkelsdorf about this issue?
