### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by tapz** [JanGorman/MapleBacon#21]
It would be nice to monitor the download progress. ImageDownloadOperation seems to have a delegate for progress, but it's private and the constructor, which takes the delegate is called in ImageManager with just the url, not with any delegate. The delegate should be implemented and it should call a progress closure provided by the downloadImageAtURL caller.

**Comment by giacomopiva** [comment]
I agree with @tapz, at the moment I need a way to get the progress and I can't find a way.

**Comment by iHamadFouad** [comment]
i agree with @tapz , i would like to have progress so hard

**Comment by LappleApple** [comment]
@JanGorman Hi -- does @tapz's ideas appeal to you, so that you'd invite him to work on it and make a PR?

**Comment by JanGorman** [comment]
5.0.0 has progress reporting
