### ISSUE TITLE
Missing 6.1.2 release @ 'CocoaPods'

### ISSUE THREAD

**Issue by lennartstolz** [JanGorman/MapleBacon#234]
According to the `CocoaPods/Specs`, the release `6.1.2` was never published to CocoaPods.
Is there any specific reason for that? :) 

https://github.com/CocoaPods/Specs/tree/fb219770ff72beb549e6820b212c34e31f0cf604/Specs/3/6/c/MapleBacon

**Comment by JanGorman** [comment]
@lennartstolz My mistake. I just pushed it now.

And sorry for the late reply, I changed to GitHub notifications a while ago and now I seem to miss half of them 🙈
