### ISSUE TITLE
Placeholder images not working with 2.0.5

### ISSUE THREAD

**Issue by tapz** [JanGorman/MapleBacon#31]
The image flashes between the placeholder and the loaded image in totally uncontrolled manner. Downgraded to 2.0.4 and works just fine.

**Comment by papertigers** [comment]
This may be related to what I saw with #33

**Comment by LappleApple** [comment]
@tapz Same question as with previous bug-related issue

**Comment by tapz** [comment]
Switched from MapleBacon to AlamofireImage...
