### ISSUE TITLE
Loading Gifs has Problems

### ISSUE THREAD

**Issue by Mahan3340** [JanGorman/MapleBacon#45]
Hi , I'm not gonna use this lib for loading gifs but I accidently uploaded a gif file and tried to load It and it was loaded successfully but whenever I launch another view controller the Image is gone ( like it was not loaded at all ) and it wont load again if I call the method till I close and reopen the app

**Comment by JanGorman** [comment]
Hi,

Thanks for the report and sorry to hear about the issue. That's interesting since it should support animated gifs. That must mean our type detection here is a bit flaky. I wrote a dedicated animated gif library so I'll see if I can re-use the code from there to detect the image type. That one uses Apple's Image I/O so definitely more robust

**Comment by Mahan3340** [comment]
thank you , i'll be waiting to hear from you

**Comment by JanGorman** [comment]
I pushed a change to https://github.com/JanGorman/MapleBacon/tree/gif-detection – can you test this branch or either share the gif that was causing issues. Thanks!

**Comment by Mahan3340** [comment]
Hi , thank you so much , it was not a specific gif , I'll test i and let you know

**Comment by Mahan3340** [comment]
I tried this with a random gif , and it was like before , launching a VC will cause the image to reset to its default image and never loads again on VC loading again even forcing it on viewDidApear

**Comment by JanGorman** [comment]
Weirdness. Even the sample app displays a random gif and never had issues. Anyways, I'll keep that in mind. I've shifted focus to the [reboot branch](https://github.com/JanGorman/MapleBacon/tree/reboot) in preparation for Swift 4 which will clean up a number of issues. We'll see how that behaves then.
