### ISSUE TITLE
XCode 10 New Build System 

### ISSUE THREAD

**Issue by serendipityfierce** [JanGorman/MapleBacon#55]
Showing Recent Messages

Prepare build
note: Using new build systemnote: Planning buildnote: Constructing build description

Build system information
warning: duplicate output file '/Users/user1/Library/Developer/Xcode/DerivedData/Jojo-iOS-eonrbjlpadwwwhdnvqnvwgpsaqve/Build/Products/Debug-iphonesimulator/MapleBacon/MapleBacon.framework/Info.plist' on task: ProcessInfoPlistFile /Users/user1/Library/Developer/Xcode/DerivedData/Jojo-iOS-eonrbjlpadwwwhdnvqnvwgpsaqve/Build/Products/Debug-iphonesimulator/MapleBacon/MapleBacon.framework/Info.plist /Users/user1/jojo-ios/Pods/Target Support Files/MapleBacon/Info.plist (in target 'MapleBacon')
Build system information
error: Multiple commands produce '/Users/neilchesterlopez/Library/Developer/Xcode/DerivedData/Jojo-iOS-eonrbjlpadwwwhdnvqnvwgpsaqve/Build/Products/Debug-iphonesimulator/MapleBacon/MapleBacon.framework/Info.plist':
1) Target 'MapleBacon' (project 'Pods') has copy command from '/Users/user1/jojo-ios/Pods/MapleBacon/MapleBacon/Info.plist' to '/Users/user1/Library/Developer/Xcode/DerivedData/Jojo-iOS-eonrbjlpadwwwhdnvqnvwgpsaqve/Build/Products/Debug-iphonesimulator/MapleBacon/MapleBacon.framework/Info.plist'
2) Target 'MapleBacon' (project 'Pods') has process command with output '/Users/user1/Library/Developer/Xcode/DerivedData/Jojo-iOS-eonrbjlpadwwwhdnvqnvwgpsaqve/Build/Products/Debug-iphonesimulator/MapleBacon/MapleBacon.framework/Info.plist'

Build failed    25/09/2018, 5:54 PM    6.8 seconds

**Comment by JanGorman** [comment]
interesting… Are you using the release tag https://github.com/JanGorman/MapleBacon/releases/tag/5.2 – I had the same issue while building the pod and the podspec update to only include Swift files (`s.source_files = 'MapleBacon/**/*.swift'`) resolved the issue

**Comment by serendipityfierce** [comment]
Thank you!
