### ISSUE TITLE
Crash on low memory

### ISSUE THREAD

**Issue by keynsianets** [JanGorman/MapleBacon#59]
We have many crashes related with MapleBacon in app. When app receive low memory warning, loading next image from cache cause to crash (as we think, maybe there are some other reasons to crash app except low memory). We can't reproduce this crash on test devices. I attach screenshots from crashlytics. 

![2019-02-14 09 49 43](https://user-images.githubusercontent.com/46818370/52771786-7ecdcc00-303f-11e9-9e29-1a22a7e92d21.png)

![2019-02-14 09 37 30](https://user-images.githubusercontent.com/46818370/52771779-7c6b7200-303f-11e9-8585-ab16bfa7aec0.png)
![2019-02-14 10 04 59](https://user-images.githubusercontent.com/46818370/52772015-1e8b5a00-3040-11e9-99a7-8b9f8d147a49.png)

![2019-02-14 10 05 33](https://user-images.githubusercontent.com/46818370/52772010-1a5f3c80-3040-11e9-8831-b1ae4c9d217a.png)

**Comment by JanGorman** [comment]
Hi,
Thanks for the report. Interesting – we use the library at work with a fairly large user base and I haven't come across this issue yet.
The line that looks like the real culprit to me is `download.data.append(data)` – so nothing "custom", only the memory allocation for `NSData`.

How big are the images that you're downloading on average?

**Comment by keynsianets** [comment]
Average image size is 2-3 MB, but for some tasks we use full-size users images and they can have size up to 10MB. And we have a lot of images in app.

**Comment by JanGorman** [comment]
Ok, thanks for the info. I'll investigate this further

**Comment by petrykDima** [comment]
I have the same issue too =(

```
code in my cell
 photoView.setImage(with: url, placeholder: nil, progress: { received, total in
                    // Report progress
                }, completion: { [weak self] image in
                    self?.activityIndicator.isHidden = true
                })
```

```
app delegate
 let oneDaySeconds: TimeInterval = 60 * 60 * 24
        Cache.default.maxCacheAgeSeconds = oneDaySeconds
```

**Comment by JanGorman** [comment]
Can you estimate how many concurrent downloads are running at one time? Considering that the line that's crashing is `download.data.append(data)` (appending downloaded data to data in memory which is freed once the download finishes) I can really only imagine that you're hitting a race condition between fetching new data and `UIApplication.didReceiveMemoryWarningNotification` kicking in which purges all data held in memory by MapleBacon.

**Comment by petrykDima** [comment]
Hi JanGorman, thank for your job. 

I use this code in tableView (action willDisplay cell). Table view can load from 2 to 8 cells, count depends to cells size and device height. 

Actually, I can't reproduce this crash. But I see how memory growing when load cells. I had commented "image downloading" and issue with memory was resolved, then uncommented "image downloading" and issue returned

I like this pod, image setups exactly without jumps and any lugs.

**Comment by JanGorman** [comment]
Hi – thanks for the additional info. I mean we definitely display _a lot_ more images in our app without problems. Memory consumption going up is to be expected. Last year's WWDC session on memory ([416](https://developer.apple.com/videos/play/wwdc2018/416/)) made an important point about optimising the image size for display if possible. Alternatively look into `ImageIO` for scaling down images since it's more efficient than `UIImage`. [ImageTransformer](https://github.com/JanGorman/MapleBacon#image-transformers) built into the library might be a framework you could look into

**Comment by JanGorman** [comment]
The [5.4.0 release](https://github.com/JanGorman/MapleBacon/releases/tag/5.4.0) adds a new `displayOptions` parameter. See the release notes for details, but the TL;DR version is that this reduces memory usage a lot. I've seen a > 50% reduction

For the record though I still think you have some memory issue hiding somewhere else 😉 – as mentioned we use the library in production and display hundreds of images in collection views without ever running into this issue.
